routes/songs.py
import os

from flask.helpers import url_for
from util import random_string
from flask.globals import request
from models.database import db_connection
from werkzeug.utils import redirect, secure_filename
from flask import Blueprint, abort, render_template, current_app, send_from_directory

bp = Blueprint('songs', __name__, url_prefix='/songs')

ALLOWED_EXTENSIONS = {'mp3'}


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# Custom static data
@bp.route('/<path:filename>')
def custom_static(filename):
    return send_from_directory(current_app.config['CUSTOM_STATIC_PATH'], filename)


@bp.route('/stream', methods=['GET'])
def stream():
    song_public_id = request.args.get('id')

    query = 'SELECT title, filename, song_public_id FROM songs WHERE song_public_id=?;'
    args = (song_public_id,)

    db = db_connection()
    get = db.get(query, args, one=True)
    if get is not None:
        title = get[0]
        filename = get[1]
        id = get[2]
        return render_template('stream.html', title=title, filename=filename, id=id)

    return 'URL is invalid'


@bp.route('/view', methods=['GET'])
def view():
    query = 'SELECT title, artist, album, song_public_id FROM songs;'

    db = db_connection()
    songs_list = db.get(query)

    if len(songs_list) == 0:
        error_message = 'No Data Found'
        return render_template('error.html', error_message=error_message)

    elif songs_list is not None:
        share_url = 'http://{}:{}/songs/stream?id='.format(current_app.config['DOMAIN_NAME'],
                                                           current_app.config['PORT'])

        delete_url = 'http://{}:{}/songs/delete?id='.format(current_app.config['DOMAIN_NAME'],
                                                            current_app.config['PORT'])

        table_col = ['Title', 'Artist', 'Album', 'Share', 'Action']

        return render_template('songs.html', table_col=table_col, share_url=share_url, delete_url=delete_url, table_row=songs_list)

    else:
        return render_template('error.html', error_message=songs_list)


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'GET':
        return render_template('upload.html')

    elif request.method == 'POST':
        title = request.form['title']
        artist = request.form['artist']
        album = request.form['album']
        song_public_id = random_string()

        if 'file' not in request.files:
            error_message = 'No file is attached'
            return render_template('error.html', error_message=error_message)

        file = request.files['file']

        if file.filename == '':
            error_message = 'No selected file'
            return render_template('error.html', error_message=error_message)

        if not file and allowed_file(file.filename) is False:
            error_message = 'Allowed only .mp3 files'
            return render_template('error.html', error_message=error_message)

        filename = title + '.mp3'
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        query = 'INSERT INTO songs(song_public_id, title, artist, album, filename) values (?, ?, ?, ?, ?);'
        args = (song_public_id, title, artist, album, filename)

        db = db_connection()
        insert = db.insert(query, args)
        if insert is not True:
            error_message = 'Error while uploading the song'
            return render_template('error.html', error_message=error_message)

        file.save(file_path)
        success_message = 'File uploaded successfully'
        return render_template('success.html', success_message=success_message)

    else:
        return abort(404)


@bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'GET':
        return render_template('search.html')

    elif request.method == 'POST':
        title = request.form['title']
        artist = request.form['artist']
        album = request.form['album']

        if title != '':
            query = "SELECT title, artist, album, song_public_id FROM songs WHERE title LIKE ?;"
            args = ("%" + title + "%", )

        elif artist != '':
            query = "SELECT title, artist, album, song_public_id FROM songs WHERE artist LIKE ?;"
            args = ("%" + artist + "%", )

        elif album != '':
            query = "SELECT title, artist, album, song_public_id FROM songs WHERE album LIKE ?;"
            args = ("%" + album + "%", )

        else:
            error_message = "Invalid song search attribute"
            return render_template("error.html", error_message=error_message)

        db = db_connection()
        songs_list = db.get(query, args)

        if len(songs_list) == 0:
            error_message = 'No Data Found'
            return render_template('error.html', error_message=error_message)

        elif songs_list is not None:
            share_url = 'http://{}:{}/songs/stream?id='.format(current_app.config['DOMAIN_NAME'],
                                                               current_app.config['PORT'])

            delete_url = 'http://{}:{}/songs/delete?id='.format(current_app.config['DOMAIN_NAME'],
                                                                current_app.config['PORT'])

            table_col = ['Title', 'Artist', 'Album', 'Share', 'Action']

            return render_template('search.html', table_col=table_col, share_url=share_url, delete_url=delete_url, table_row=songs_list)

        else:
            error_message = 'No Data Found'
            return render_template('error.html', error_message=error_message)

    else:
        abort(404)


@bp.route('/delete', methods=['GET'])
def delete():
    song_public_id = request.args.get('id')

    query = 'DELETE FROM songs WHERE song_public_id=?;'
    args = (song_public_id,)

    db = db_connection()
    delete = db.delete(query, args)
    if delete is True:
        success_message = 'Song deleted successfully'
        return render_template('success.html', success_message=success_message)

    else:
        error_message = delete
        return render_template('error.html', error_message=error_message)


@bp.route('/download', methods=['GET'])
def download():
    song_public_id = request.args.get('id')

    query = 'SELECT filename FROM songs WHERE song_public_id=?;'
    args = (song_public_id,)

    db = db_connection()
    get = db.get(query, args, one=True)

    if len(get) == 0:
        error_message = 'No Data Found'
        return render_template('error.html', error_message=error_message)

    elif get is not None:
        filename = get[0]
    
    else:
        return render_template('error.html', error_message=get)

    directory = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'])
    return send_from_directory(directory=directory, filename=filename, as_attachment=True)

templates/delete.html
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>
    <p>{{ success_message }}</p>
</body>

</html>

templates/error.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>
    <p>{{ error_message }}</p>
    
</body>

</html>

templates/search.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>

    <form method="POST" class="" action="{{ url_for('songs.search') }}">
        <p>Title : <input type="text" name="title" placeholder="Search by title">
            <button>search</button><br><br></p>
        <p>Artist : <input type="text" name="artist" placeholder="Search by artist">
            <button>search</button><br><br></p>
        <p>Album : <input type="text" name="album" placeholder="Search by Album">
            <button>search</button></p>
    </form>
    <br><br>

    <table class="center">
        <tr>
            {% for col in table_col %}
            <th>{{ col }}</th>
            {% endfor %}
        </tr>
        {% for row in table_row %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td><a href={{share_url}}{{row[3]}}>Stream</a></td>
            <td><a href={{delete_url}}{{row[3]}}>Delete</a></td>
        </tr>
        {% endfor %}

    </table>

</body>

</html>

templates/songs.html
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>

    <table class="center">

        <tr>
            {% for col in table_col %}
            <th>{{ col }}</th>
            {% endfor %}
        </tr>
        {% for row in table_row %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td><a href={{share_url}}{{row[3]}}>Stream</a></td>
            <td><a href={{delete_url}}{{row[3]}}>Delete</a></td>
        </tr>
        {% endfor %}

    </table>

</body>

</html>

templates/stream.html
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>
    <p>{{ title }}</p>
    <audio controls>
        <source src="{{ url_for('songs.custom_static', filename='') }}{{ domain_name }}{{ filename }}"
            type="audio/mpeg">
    </audio>
    <br><br>
    <form method="GET" action="{{ url_for('songs.download') }}">
        <input type="hidden" name="id" value={{id}} /> 
        <input type="submit" value="Download" />
    </form>

</body>

</html>

templates/success.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %} Music Manager</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>
</head>

<body>
    <br>
    <div class="in-middle">
        <ul class="menu">
            <a href="{{ url_for('songs.view') }}">SONGS</a>
            <a href="{{ url_for('songs.upload') }}">UPLOAD</a>
            <a href="{{ url_for('songs.search') }}">SEARCH</a>
        </ul>
    </div>
    <br><br><br>
    {{ success_message }}
</body>

</html>

templates/upload.html
<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}{% endblock %} Music Manager</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='songs.css') }}">
</head>
</head>

<body>
	<br>
	<div class="in-middle">
		<ul class="menu">
			<a href="{{ url_for('songs.view') }}">SONGS</a>
			<a href="{{ url_for('songs.upload') }}">UPLOAD</a>
			<a href="{{ url_for('songs.search') }}">SEARCH</a>
		</ul>
	</div>
	<br><br><br>

	<form method="POST" action="{{ url_for('songs.upload') }}" enctype="multipart/form-data">
		<p>Title: <input type="text" name="title" value="Call it what you want"></p> <br>
		<p>Arist: <input type="text" name="artist" value="Taylor Swift"> </p><br> <br>
		<p>Album: <input type="text" name="album" value="Reputation"> </p><br> <br>
		<table>
			<ul>
				<input type="file" name="file">
				<button>Upload</button>
			</ul>
		</table>

	</form>

</body>

</html>